package com.bmw.remotecollab.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.*;


@Data
@DynamoDBTable(tableName = "rooms")
@NoArgsConstructor
public class Room {

    @DynamoDBHashKey
    private String id;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date lastUpdate;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "members")
    private List<Member> members;

    public Room(String name) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
    }

    public void addMember(Member member) {
        if(members == null) {
            members = new ArrayList<>();
        }
        if(!members.contains(member)) {
            this.members.add(member);
        }
    }

    public void addMembers(Collection<Member> members) {
        members.forEach(this::addMember);
    }
}
