package com.bmw.remotecollab.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.*;


@Data
@DynamoDBTable(tableName = "rooms")
public class Room {

    @DynamoDBHashKey
    private String id;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date lastUpdate;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    private final Set<Member> members = new HashSet<>();

    public Room(String name) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
    }

    // Needed for dynamodb
    @SuppressWarnings("unused")
    public Room() {
    }

    public void addMember(Member member) {
        this.members.add(member);
    }

    public void addMembers(Collection<Member> members) {
        this.members.addAll(members);
    }
}
