version: '3.1'

services:

  # openvidu-server:
  #   image: 'openvidu/openvidu-server-kms:latest'
  #   hostname: openvidu-server
  #   container_name: openvidu-server
  #   ports:
  #   - 4443:4443
  #   environment:
  #     openvidu.secret: secret

  viper-service-remote-collab-admin:
    build: ./viper-service-remote-collab-admin
    hostname: viper-service-remote-collab-admin
    container_name: viper-service-remote-collab-admin
    ports:
    - 8080:8080
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-session:8000/
      # Note: even though these keys are garbage values, access key and
      # secret key are still required. Otherwise, `aws-sdk` will attempt
      # to read credentials from Amazon's `169.254.169.254` service and
      # fail.
      AWS_ACCESS_KEY_ID: keys
      AWS_SECRET_ACCESS_KEY: secret
    depends_on:
    - dynamodb-session

  dynamodb-session:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-session
    hostname: dynamodb-session
    ports:
    - 8000:8000

  viper-ui-remote-collab-admin:
    build: ./viper-ui-remote-collab-admin
    hostname: viper-ui-remote-collab-admin
    container_name: viper-ui-remote-collab-admin
    ports:
    - 8081:8081
