version: '3.1'

services:
  openvidu-server:
    image: 'openvidu/openvidu-server-kms:latest'
    hostname: openvidu-server
    container_name: openvidu-server
    ports:
      - 4443:4443
    environment:
      openvidu.secret: MY_SECRET

  dynamodb-session:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-session
    hostname: dynamodb-session

  remote-collab-rest-api:
    build: .
    hostname: remote-collab-rest-api
    container_name: remote-collab-rest-api
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY_ID: <DUMMY_VALUE_FOR_LOCAL_DYNAMODB>
      AWS_SECRET_KEY:  <DUMMY_VALUE_FOR_LOCAL_DYNAMODB>
    depends_on:
      - dynamodb-session