version: '3.1'

services:
  openvidu-server:
    image: 'openvidu/openvidu-server-kms:latest'
    hostname: openvidu-server
    container_name: openvidu-server
    ports:
      - 4443:4443
    environment:
      openvidu.secret: MY_SECRET

  dynamodb-room-store:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-room-store
    hostname: dynamodb-room-store
    ports:
      - 8000:8000

  remote-collab-rest-api:
    build: .
    hostname: remote-collab-rest-api
    container_name: remote-collab-rest-api
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY_ID: AKIAR2T7SJUE2A2J5XQM
      AWS_SECRET_KEY:  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
    depends_on:
      - dynamodb-room-store
